// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/invoices": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/alerts": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/discounts": {
    params: {};
  };
  "/cashier-profile": {
    params: {};
  };
  "/customer-discounts": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/billing" | "/invoices" | "/history" | "/analytics" | "/alerts" | "/profile" | "/settings" | "/discounts" | "/cashier-profile" | "/customer-discounts" | "/logout" | "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/products" | "/billing" | "/invoices" | "/history" | "/analytics" | "/alerts" | "/profile" | "/settings" | "/discounts" | "/cashier-profile" | "/customer-discounts" | "/logout";
  };
  "routes/_app.dashboard.tsx": {
    id: "routes/_app.dashboard";
    page: "/";
  };
  "routes/_app.products.tsx": {
    id: "routes/_app.products";
    page: "/products";
  };
  "routes/_app.billing.tsx": {
    id: "routes/_app.billing";
    page: "/billing";
  };
  "routes/_app.invoices.tsx": {
    id: "routes/_app.invoices";
    page: "/invoices";
  };
  "routes/_app.history.tsx": {
    id: "routes/_app.history";
    page: "/history";
  };
  "routes/_app.analytics.tsx": {
    id: "routes/_app.analytics";
    page: "/analytics";
  };
  "routes/_app.alerts.tsx": {
    id: "routes/_app.alerts";
    page: "/alerts";
  };
  "routes/_app.profile.tsx": {
    id: "routes/_app.profile";
    page: "/profile";
  };
  "routes/_app.settings.tsx": {
    id: "routes/_app.settings";
    page: "/settings";
  };
  "routes/_app.discounts.tsx": {
    id: "routes/_app.discounts";
    page: "/discounts";
  };
  "routes/_app.cashierProfile.tsx": {
    id: "routes/_app.cashierProfile";
    page: "/cashier-profile";
  };
  "routes/_app.customerDiscounts.tsx": {
    id: "routes/_app.customerDiscounts";
    page: "/customer-discounts";
  };
  "routes/_app.logout.tsx": {
    id: "routes/_app.logout";
    page: "/logout";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.dashboard": typeof import("./app/routes/_app.dashboard.tsx");
  "routes/_app.products": typeof import("./app/routes/_app.products.tsx");
  "routes/_app.billing": typeof import("./app/routes/_app.billing.tsx");
  "routes/_app.invoices": typeof import("./app/routes/_app.invoices.tsx");
  "routes/_app.history": typeof import("./app/routes/_app.history.tsx");
  "routes/_app.analytics": typeof import("./app/routes/_app.analytics.tsx");
  "routes/_app.alerts": typeof import("./app/routes/_app.alerts.tsx");
  "routes/_app.profile": typeof import("./app/routes/_app.profile.tsx");
  "routes/_app.settings": typeof import("./app/routes/_app.settings.tsx");
  "routes/_app.discounts": typeof import("./app/routes/_app.discounts.tsx");
  "routes/_app.cashierProfile": typeof import("./app/routes/_app.cashierProfile.tsx");
  "routes/_app.customerDiscounts": typeof import("./app/routes/_app.customerDiscounts.tsx");
  "routes/_app.logout": typeof import("./app/routes/_app.logout.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};