ALTER TABLE `User`
  MODIFY `role` ENUM('ADMIN', 'MANAGER', 'CASHIER', 'STAFF') NOT NULL DEFAULT 'CASHIER';

ALTER TABLE `Customer`
  MODIFY `createdByRole` ENUM('ADMIN', 'MANAGER', 'CASHIER', 'STAFF') NULL;
